listando/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
]

main/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path, include  #add include


app_name = "main"   


urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),
    path("sucesso", views.sucesso, name="sucesso")
]

main/models.py
from djongo import models
from django.contrib.auth import get_user_model


class Stats(models.Model):
    user = models.CharField(max_length=100, primary_key=True)

    listas_completas = models.IntegerField(default=0)
    questoes_completas = models.IntegerField(default=0)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
# Create your forms here.


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class ListaDeQuestoes(forms.Form):
    def __init__(self, choices=None, *args, **kwargs):
        super(ListaDeQuestoes, self).__init__(*args, **kwargs)
        if choices:
            for tema, max_value in choices:
                self.fields[tema] = forms.IntegerField(
                    initial=0, label=tema, min_value=0, max_value=max_value)

main/views.py
from math import floor
from django.shortcuts import render, redirect
from .forms import NewUserForm, ListaDeQuestoes
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse
from . import geraPDF
import io
from .models import Stats


def homepage(request):
    if request.user.is_anonymous:
        return render(request=request, template_name='main/index.html')
    stats, created = Stats.objects.get_or_create(
        user=request.user.username)

    emblema = None
    if stats.questoes_completas > 1:
        emblema = 'bronze'
    if stats.questoes_completas > 3:
        emblema = 'prata'
    if stats.questoes_completas > 6:
        emblema = 'ouro'

    context = {
        'username': request.user.username,
        'n': stats.listas_completas,
        'q': stats.questoes_completas,
        'lvl': floor(stats.questoes_completas/100),
        'emblema': emblema
    }
    return render(request=request, template_name='main/index.html', context=context)


@login_required
def sucesso(request):
    choices = geraPDF.get_temas()
    if request.method == "GET":
        form = ListaDeQuestoes(choices=choices)

        context = {
            'form': form,
        }
        return render(request, 'main/sucesso.html', context=context)
    else:
        form = ListaDeQuestoes(data=request.POST, choices=choices)

        if form.is_valid():
            data = {tema: form.cleaned_data.get(
                tema) for tema, maxno in choices}

            buffer = io.BytesIO()
            geraPDF.gerarPDF(data, buffer)
            response = HttpResponse(content_type='application/pdf')
            response['Content-Disposition'] = 'attachment; filename=lista_personalizada.pdf'
            response.write(buffer.getvalue())
            buffer.close()

            stats, created = Stats.objects.get_or_create(
                user=request.user.username)
            stats.listas_completas += 1
            stats.questoes_completas += sum(list(data.values()))
            stats.save()

            return response
        else:
            form = ListaDeQuestoes(choices=choices)

            context = {
                'form': form,
            }
            return render(request, 'main/sucesso.html', context=context)


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            Stats.objects.create(user=user.username)
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("main:login")
        messages.error(
            request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="main/register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("main:sucesso")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="main/login.html", context={"login_form": form})


@login_required
def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("main:homepage")

main/templates/main/header.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <img src="{% static 'icon.png' %}" width="60" height="60">
    <style>
      body {
        background-color: #FFE184;
      }
    </style>

    <title>Listando</title>
  </head>
 <body>

    {% block content %}

    {% endblock %} 
      
  </body>
</html>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="SHORTCUT ICON"
      href="https://www.google.com/url?sa=i&url=https%3A%2F%2Fpt.wikipedia.org%2Fwiki%2FUniversidade_Federal_de_S%25C3%25A3o_Paulo&psig=AOvVaw0bRARXm2j4hJyZv0-VbKtY&ust=1668108907513000&source=images&cd=vfe&ved=0CA0QjRxqFwoTCNDmgYvsofsCFQAAAAAdAAAAABAD"
    />
    <style>
      body {
        background-color: #ffe184;
      }
    </style>
    <title>Listando</title>
  </head>

  <body>
    <div align="center">
      <header>
        {% load static %}
        <img src="{% static 'capa.png' %}" width="450" height="159" />
      </header>

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <div class="nav-item">
            <div>Bem vindo, {{username|safe}} - Nível {{lvl|safe}}.</div>
            <div>
              Você completou {{n|safe}} listas, totalizando {{q|safe}} questões!
            </div>
            <br></br>
            {% if emblema != None %}
              {% with emblema|add:'.png' as emblema_static %}
                <img src="{% static emblema_static %}" width="169" height="295" />
              {% endwith %}
              <br></br>
              <div>
                Você conquistou o emblema {{emblema | safe}}!
              </div>
              <br></br>
            {% endif %}
            <div class="nav-item">
              <a class="nav-link" href="{% url 'main:sucesso' %}"
                >Gerar listas</a
              >
            </div>
            <br></br>
            <div class="nav-item">
              <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
            </div>
          </div>
          {% else %}
          <div><a href="{% url 'main:register' %}">Registre-se</a></div>
          <div class="nav-item">
            <a class="nav-link" href="{% url 'main:login' %}">Entrar</a>
          </div>

          {% endif %}
        </ul>
      </nav>
    </div>
  </body>
</html>

main/templates/main/login.html
{% extends "main/header.html" %}

{% block content %}      

{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <div class="text-center">
    <h1>Login</h1>
    <h4></h4>
    <form method="POST">
      {% csrf_token %}
      {{ login_form|crispy }}
      <h4></h4>
      <button class="btn btn-primary" type="submit">Entrar</button>
    </form>
    <p class="text-center">Ainda não tem uma conta? <a href="/register">Registre-se</a>.</p>
  </div>
</div>

{% endblock %}

main/templates/main/register.html
{% extends "main/header.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Registre-se</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Registrar</button>
	</form>
	<p class="text-center">Se você já tem uma conta, <a href="/login">entre aqui</a>.</p>
</div>
{% endblock %}

main/templates/main/sucesso.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8" />
    <title>Listando</title>
    {% load static %}
    <link rel="SHORTCUT ICON" img src="{% static 'icon.png' %}" />

    <style>
      body {
        background-color: #ffe184;
      }
      .capa {
        margin: auto;
        padding: 10px;
        width: 30%;
      }
      .texto {
        text-align: center;
      }
      .submit-button {
        margin: auto;
        width: 50%;
        border: 3px solid green;
        padding: 10px;
      }
      .grande {
        font-size: 30px;
        font-weight: bold;
      }
    </style>
  </head>

  <body>
    <div class="capa">
      <header align="center">
        {% load static %}
        <img src="{% static 'capa.png' %}" width="400" height="141" />
      </header>
    </div>
    <div class="texto">
      <a href="{% url 'main:homepage' %}"> Página inicial </a>
      <br></br>
    </div>
    <!--Register-->
    <div class="texto grande">Monte aqui sua lista!</div>
    <div class="texto">
      Informe a quantidade de questões que você deseja de cada assunto:
    </div>
    <br></br>
    <div align="center">
      <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <br></br>
        <input type="submit" value="Gerar Lista" class="submit-button" />
      </form>
    </div>
  </body>
</html>